### ISSUE TITLE
lua errors

### ISSUE THREAD

**Issue by bschilder** [js2264/BiocBook#7]
Upgraded to Quarto 1.4 and started getting these errors which hadn't come up before. Haven't been able to pinpoint where it's coming from.

```
==> quarto preview chapter1.qmd --to html --no-watch-inputs --no-browse



processing file: chapter1.qmd
  |......                          |  19%                                      HP:0033127
Translating ontology terms to ids.
  |..........                      |  30%                                      Registered S3 method overwritten by 'ggside':
  method from   
  +.gg   ggplot2
  |...........................     |  86%                                      + Version: 2024-02-08
                                                                                                                                
output file: chapter1.knit.md

pandoc 
  to: html
  from: markdown+emoji
  output-file: chapter1.html
  standalone: true
  toc: true
  number-sections: false
  title-prefix: PhD Thesis <br>Brian M. Schilder
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  dpi: 300
  number-offset:
    - 4
  
metadata
  crossref:
    chapters: true
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  csl: ../../assets/nature-medicine.csl
  knitr:
    opts_chunk:
      collapse: true
      comment: '## '
      fig.align: center
      python.reticulate: false
      R.options:
        dplyr.print_min: 6
        dplyr.print_max: 6
        pillar.max_footer_lines: 2
        pillar.min_chars: 15
        stringr.view_n: 6
        pillar.bold: true
        width: 77
  grid:
    sidebar-width: 500px
    body-width: 800px
  theme:
    - cosmo
    - ../../assets/book.scss
  editor: visual
  title: '[Aim 1. Discover the cell types underlying rare disease phenotypes]{.chapter-title}'
  bibliography:
    - references.bib
  hide-description: true
  
ERROR (/Applications/quarto/share/pandoc/datadir/_json.lua:193) unexpected character 'S' at line 1 col 1
Error running filter /Applications/quarto/share/filters/main.lua:
/Applications/quarto/share/pandoc/datadir/_json.lua:174: bad 'for' initial value (number expected, got nil)
stack traceback:
	/Applications/quarto/share/pandoc/datadir/_json.lua:388: in function '_json.decode'
	/Applications/quarto/share/filters/main.lua:15151: in local 'fn'
	/Applications/quarto/share/filters/main.lua:2554: in function </Applications/quarto/share/filters/main.lua:2548>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	/Applications/quarto/share/filters/main.lua:224: in function </Applications/quarto/share/filters/main.lua:214>
	(...tail calls...)
	/Applications/quarto/share/filters/main.lua:942: in local 'callback'
	/Applications/quarto/share/filters/main.lua:960: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:996: in function </Applications/quarto/share/filters/main.lua:993>
stack traceback:
	/Applications/quarto/share/filters/main.lua:224: in function </Applications/quarto/share/filters/main.lua:214>
	(...tail calls...)
	/Applications/quarto/share/filters/main.lua:942: in local 'callback'
	/Applications/quarto/share/filters/main.lua:960: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:996: in function </Applications/quarto/share/filters/main.lua:993>
```

# Potentially related issues
- https://github.com/quarto-dev/quarto-cli/issues/5392
- https://github.com/quarto-dev/quarto-cli/issues/6013#issuecomment-1604700946
- https://github.com/quarto-dev/quarto-cli/issues/2013
- https://github.com/quarto-dev/quarto-cli/issues/1378
- https://github.com/quarto-dev/quarto-cli/issues/4225

**Comment by bschilder** [comment]
Changing the yaml header didn't help:

```
---
title: "Aim 1. Discover the cell types underlying rare disease phenotypes"
bibliography: references.bib
execute:
  cache: true
  message: false
  warning: false 
---
```

```
---
title: "Aim 1. Discover the cell types underlying rare disease phenotypes"
bibliography: references.bib
---
```

**Comment by bschilder** [comment]
Maybe related to changes in Quarto lua extensions?

https://quarto.org/docs/prerelease/1.4/lua_changes.html

**Comment by bschilder** [comment]
I think i figured it out!!

Made a minimal example BiocBook here to test it out in:
https://github.com/bschilder/BBreprex

The copied my __format.yml_ in which I was getting the errors. Then I hashed out my parameters one by one to see if any of them caused the Lua issues I observed before.

`echo: false` seems to cause problems in the format file for `pdf` and `docx`, but not `html`. Maybe I'm using it incorrectly here, and it's causing problems when Quarto tries to interpret it?

```yml
format: 
  html:
    output-dir: docs
    execute:
      keep-md: true
      echo: true
      message: false
      warning: false
    grid:
      sidebar-width: 500px
      body-width: 800px
    theme: 
      - cosmo
      - assets/book.scss
    number-sections: false
    dpi: 300
    highlight-style: atom-one
    code-fold: true
    from: markdown+emoji 
  pdf:
    output-dir: pdf
    execute:
      keep-md: true
      echo: false
      message: false
      warning: false
  docx:
    output-dir: docx
    execute:
      keep-md: true
      echo: false
      message: false
      warning: false 

```

**Comment by bschilder** [comment]
Well, partway there at least, getting a different error now but will document that as a separate issue and try using the same approach to debug.

**Comment by bschilder** [comment]
Weird, from the Quarto docs seems like `echo: false` should work in PDF too:
https://quarto.org/docs/reference/formats/pdf.html#execution

**Comment by bschilder** [comment]
Note, it does seem to work when put in the yaml header of a single .qmd file. I think this may be because knitr is being triggered as the engine when R code chunks are found inside the file. But the same doesn't happen at the project level when you specify it within _format.yml

```yml
---
title: "Aim 1. Discover the cell types underlying rare disease phenotypes"
bibliography: references.bib
format:
  pdf:
    execute:
      cache: true
      echo: false
      message: false
      warning: false
---
```
